# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aidoku < Formula
  desc "Aidoku development toolkit"
  homepage "https://github.com/beerpiss/aidoku-cli"
  version "0.3.0"
  license "0BSD"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/beerpiss/aidoku-cli/releases/download/v0.3.0/aidoku_0.3.0_macos_arm64.tar.gz"
      sha256 "e307112626b355175038a97a3b7402b587a66f73cec9b61679d960d69c07a403"

      def install
        bin.install "aidoku"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/beerpiss/aidoku-cli/releases/download/v0.3.0/aidoku_0.3.0_macos_x86_64.tar.gz"
      sha256 "c3b353345cf4b1f044531dca77d2c0f1d228f99692110be5270697415d91cf7c"

      def install
        bin.install "aidoku"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/beerpiss/aidoku-cli/releases/download/v0.3.0/aidoku_0.3.0_linux_x86_64.tar.gz"
      sha256 "12cc5081d1ca4116057b29cdd2aac4eba128d6603a499d400b9cef81e57ad848"

      def install
        bin.install "aidoku"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/beerpiss/aidoku-cli/releases/download/v0.3.0/aidoku_0.3.0_linux_arm64.tar.gz"
      sha256 "0d04d76d841fa1a4c592959179ee54739a280789f2e742ff6e64ea1d89cc2805"

      def install
        bin.install "aidoku"
      end
    end
  end

  test do
    system "#{bin}/aidoku version"
  end
end
