# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AidokuCli < Formula
  desc "Aidoku development toolkit"
  homepage "https://github.com/Aidoku/aidoku-cli"
  version "0.5.6"
  license "0BSD"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Aidoku/aidoku-cli/releases/download/v0.5.6/aidoku-cli_0.5.6_macos_x86_64.tar.gz"
      sha256 "5732f35cf3928029ebbd693a5d7d12a2205a05a34bd208c6ddeecb7c96e2eb0f"

      def install
        bin.install "aidoku"
        (bash_completion/"aidoku").write `#{bin}/aidoku completion bash`
        (zsh_completion/"_aidoku").write `#{bin}/aidoku completion zsh`
        (fish_completion/"aidoku.fish").write `#{bin}/aidoku completion fish`
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Aidoku/aidoku-cli/releases/download/v0.5.6/aidoku-cli_0.5.6_macos_arm64.tar.gz"
      sha256 "3e1b9a59b5d7dbd21ad238dbec4871b50bc5e42eef2680b8fcd670faa66b89a4"

      def install
        bin.install "aidoku"
        (bash_completion/"aidoku").write `#{bin}/aidoku completion bash`
        (zsh_completion/"_aidoku").write `#{bin}/aidoku completion zsh`
        (fish_completion/"aidoku.fish").write `#{bin}/aidoku completion fish`
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Aidoku/aidoku-cli/releases/download/v0.5.6/aidoku-cli_0.5.6_linux_arm64.tar.gz"
      sha256 "447f72aa5b2e8662acbb1bd2c9988d16ed0e02691048ee290d00c292d6999257"

      def install
        bin.install "aidoku"
        (bash_completion/"aidoku").write `#{bin}/aidoku completion bash`
        (zsh_completion/"_aidoku").write `#{bin}/aidoku completion zsh`
        (fish_completion/"aidoku.fish").write `#{bin}/aidoku completion fish`
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Aidoku/aidoku-cli/releases/download/v0.5.6/aidoku-cli_0.5.6_linux_x86_64.tar.gz"
      sha256 "8293812a7950f65ca44d6b56d393725871df40988fec38ad3abe08de7483879f"

      def install
        bin.install "aidoku"
        (bash_completion/"aidoku").write `#{bin}/aidoku completion bash`
        (zsh_completion/"_aidoku").write `#{bin}/aidoku completion zsh`
        (fish_completion/"aidoku.fish").write `#{bin}/aidoku completion fish`
      end
    end
  end

  test do
    system "#{bin}/aidoku --version"
  end
end
