# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aidoku < Formula
  desc "Aidoku development toolkit"
  homepage "https://github.com/beerpiss/aidoku-cli"
  version "0.1.4"
  license "0BSD"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/beerpiss/aidoku-cli/releases/download/v0.1.4/aidoku_0.1.4_macos_x86_64.tar.gz"
      sha256 "bbcdec0211110a71f097d3963620145a689da37e278587cca38a3eefc593f790"

      def install
        bin.install "aidoku"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/beerpiss/aidoku-cli/releases/download/v0.1.4/aidoku_0.1.4_macos_arm64.tar.gz"
      sha256 "d06c15d780fb223df964942e8128180e622efca8b2778691e45ff71a3f8188e7"

      def install
        bin.install "aidoku"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/beerpiss/aidoku-cli/releases/download/v0.1.4/aidoku_0.1.4_linux_x86_64.tar.gz"
      sha256 "b31d2040eda49d0e132f1ba51917e1f9fdf23c1010be7808371edbcca131bcf8"

      def install
        bin.install "aidoku"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/beerpiss/aidoku-cli/releases/download/v0.1.4/aidoku_0.1.4_linux_arm64.tar.gz"
      sha256 "b34e2343a981ee12f7fc1f67290eb8d7de62ab660135a43b07f89fc189518b09"

      def install
        bin.install "aidoku"
      end
    end
  end

  test do
    system "#{bin}/aidoku version"
  end
end
