# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Aidoku < Formula
  desc "Aidoku development toolkit"
  homepage "https://github.com/beerpiss/aidoku-cli"
  version "0.2.1"
  license "0BSD"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/beerpiss/aidoku-cli/releases/download/v0.2.1/aidoku_0.2.1_macos_arm64.tar.gz"
      sha256 "6785867d3cb3d41c54bb3862478b90668ae19acecf7bb4e482aa6e05d9c7e89c"

      def install
        bin.install "aidoku"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/beerpiss/aidoku-cli/releases/download/v0.2.1/aidoku_0.2.1_macos_x86_64.tar.gz"
      sha256 "3570f4cee889fa41e7fb8b11d23ad99a461c6e74ab8099c684ab1a35873a429b"

      def install
        bin.install "aidoku"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/beerpiss/aidoku-cli/releases/download/v0.2.1/aidoku_0.2.1_linux_x86_64.tar.gz"
      sha256 "2d5409b7cfb96cbe4d577b21f449545e46a59f09e5f0d6f99ecf35e5445fc798"

      def install
        bin.install "aidoku"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/beerpiss/aidoku-cli/releases/download/v0.2.1/aidoku_0.2.1_linux_arm64.tar.gz"
      sha256 "1278847aeb5cd236013a414974bd713e473fef3da841b160bce761518158d96a"

      def install
        bin.install "aidoku"
      end
    end
  end

  test do
    system "#{bin}/aidoku version"
  end
end
