# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AidokuCli < Formula
  desc "Aidoku development toolkit"
  homepage "https://github.com/Aidoku/aidoku-cli"
  version "0.4.3"
  license "0BSD"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Aidoku/aidoku-cli/releases/download/v0.4.3/aidoku-cli_0.4.3_macos_x86_64.tar.gz"
      sha256 "df17bfa8b8567333ebf7fb97f77731cad319dffc63916c4ba0f7e363b117a5e1"

      def install
        bin.install "aidoku"
        (bash_completion/"aidoku").write `#{bin}/aidoku completion bash`
        (zsh_completion/"_aidoku").write `#{bin}/aidoku completion zsh`
        (fish_completion/"aidoku.fish").write `#{bin}/aidoku completion fish`
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Aidoku/aidoku-cli/releases/download/v0.4.3/aidoku-cli_0.4.3_macos_arm64.tar.gz"
      sha256 "bf2d38c11d2b122d30ed1cc6d1971ae55cd5e8d4a3febb48e09ad7cd42bf66e4"

      def install
        bin.install "aidoku"
        (bash_completion/"aidoku").write `#{bin}/aidoku completion bash`
        (zsh_completion/"_aidoku").write `#{bin}/aidoku completion zsh`
        (fish_completion/"aidoku.fish").write `#{bin}/aidoku completion fish`
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Aidoku/aidoku-cli/releases/download/v0.4.3/aidoku-cli_0.4.3_linux_arm64.tar.gz"
      sha256 "e284b9c776bf59517cc6ee553d481df224e1f00b6fac7854bf28518aa8ff7486"

      def install
        bin.install "aidoku"
        (bash_completion/"aidoku").write `#{bin}/aidoku completion bash`
        (zsh_completion/"_aidoku").write `#{bin}/aidoku completion zsh`
        (fish_completion/"aidoku.fish").write `#{bin}/aidoku completion fish`
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Aidoku/aidoku-cli/releases/download/v0.4.3/aidoku-cli_0.4.3_linux_x86_64.tar.gz"
      sha256 "94fbdc1a68e9927eb2ef6a955f0978f30ec5bbeda70076a2432cb3b2aa6f561e"

      def install
        bin.install "aidoku"
        (bash_completion/"aidoku").write `#{bin}/aidoku completion bash`
        (zsh_completion/"_aidoku").write `#{bin}/aidoku completion zsh`
        (fish_completion/"aidoku.fish").write `#{bin}/aidoku completion fish`
      end
    end
  end

  test do
    system "#{bin}/aidoku --version"
  end
end
